### ISSUE TITLE
Your Gmail password for cyantarek.cg@gmail.com is ​zxcv5555​.

### ISSUE THREAD

**Issue by NatoBoram** [cyantarek/go-playground-revamped#2]
From : https://github.com/cyantarek/go-playground-revamped/blob/master/backend/config/config.dev.yml

```yaml
server:
  grpc:
    host: "0.0.0.0"
    port: "5200"
  grpc_web:
    host: "0.0.0.0"
    port: "5300"
db:
  couchbase:
    host: "0.0.0.0"
    port: "8091"
    user: "Administrator"
    password: "password"
    bucket:
      name: "shorter"
      password: "shorter"
  bolt:
    name: "my.db"
smtp:
  host: "smtp.gmail.com"
  port: "587"
  username: "cyantarek.cg@gmail.com"
  password: "zxcv5555"
security:
  tls:
    key_file: "keys/server.key"
    cert_file: "keys/server.crt"
worker:
  count: 5
```

What the hell do you think you're doing?
